In [1]:
import numpy as np
import pandas as pd

In [2]:
_input = pd.Series([1,2,3,4,5,6,1,2,3,4,1,2,3,4,5,1,2,1,2,3,4,5,6,7,8,9])
target = pd.Series([6, 5, 4, 3, 2, 1, 4, 3, 2, 1, 5, 4, 3, 2, 1, 2, 1, 9, 8, 7, 6, 5,4, 3, 2, 1])

### Buscamos los índices del dataframe donde comienza una nueva serie

In [3]:
max_values = _input.where(_input.shift(-1) < _input, np.nan)
idx_max = max_values[max_values.notnull()].index
idx_max

Int64Index([5, 9, 14, 16], dtype='int64')

Las dos líneas anteriores podemos comprimirlas en la siguiente. 
```python
idx_max = _input[_input.where(_input.shift(-1) < _input, np.nan).notnull()].index

```


### Separamos las distintas series mediante la función array_split de numpy

In [4]:
splits = np.array_split(_input.values, idx_max + 1, axis=0)
splits

[array([1, 2, 3, 4, 5, 6]),
 array([1, 2, 3, 4]),
 array([1, 2, 3, 4, 5]),
 array([1, 2]),
 array([1, 2, 3, 4, 5, 6, 7, 8, 9])]

### Ahora las unimos ordenándolas en orden inverso previamente

In [5]:
final = pd.Series(np.hstack([ar[::-1] for ar in splits]))

In [6]:
final

0     6
1     5
2     4
3     3
4     2
5     1
6     4
7     3
8     2
9     1
10    5
11    4
12    3
13    2
14    1
15    2
16    1
17    9
18    8
19    7
20    6
21    5
22    4
23    3
24    2
25    1
dtype: int64

In [7]:
np.allclose(final.values, target.values)

True